services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask_app:
    build: .
    restart: unless-stopped
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`backend.im3wrap.my.id`)
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.tls.certresolver=mytlschallenge
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    depends_on:
      - redis
      - db

  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info --events
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://myuser:mypassword@db:5432/im3wrap
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - flask_app

  flower:
    build: .
    command: celery -A app.celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: im3wrap
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persistent storage

volumes:
  redis_data: