"""empty message

Revision ID: 82b0e0a8b2bc
Revises: b478e615ef59
Create Date: 2025-01-26 09:16:44.723859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b0e0a8b2bc'
down_revision = 'b478e615ef59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvr_code', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('discount_price', sa.Integer(), nullable=False),
    sa.Column('normal_price', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pvr_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    # ### end Alembic commands ###
