from enum import Enum

class TaskStatus(Enum):
    """Task status enumeration"""
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    CHECKING_ELIGIBILITY = "CHECKING_ELIGIBILITY"
    WAITING_FOR_ELIGIBILITY = "WAITING_FOR_ELIGIBILITY"
    INITIATING_PAYMENT = "INITIATING_PAYMENT"
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"

class TaskResult(Enum):
    """Task result types"""
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN"
    PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
    FAILED_TO_CHECK_PACKAGE_ELIGIBILITY = "FAILED_TO_CHECK_PACKAGE_ELIGIBILITY"
    PACKAGE_MIGHT_NOT_BE_ELIGIBLE_TO_BUY = "PACKAGE_MIGHT_NOT_BE_ELIGIBLE_TO_BUY"
    FAILED_TO_INITIATE_PAYMENT = "FAILED_TO_INITIATE_PAYMENT"
    PAYMENT_INITIATED_SUCCESSFULLY = "PAYMENT_INITIATED_SUCCESSFULLY"